#!/bin/sh
#
# @license http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2014 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    purge)
        # Remove the configuration data
        omv_config_delete "/config/services/gateone"

        rm -rf /etc/gateone
    ;;

    remove)
        rm -f /etc/init.d/gateone
        rm -f /etc/init/gateone.conf
        rm -rf /usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg
        rm -rf /usr/local/bin/gateone
        rm -rf /root/gateone
        
        if [ -f /etc/nginx/openmediavault-webgui.d/openmediavault-gateone.conf ]; then
            rm -f /etc/nginx/openmediavault-webgui.d/openmediavault-gateone.conf
        fi

        invoke-rc.d nginx restart
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear|remove)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
